### ISSUE TITLE
Get nginx starting failed

### ISSUE THREAD

**Issue by ghost** [GrexAut/logocontrol#1]
@GrexAut 
When I start this docker container I get a:
Nginx failed to start:
2020-04-13 08:42:11 Service crashed with exit code 255. Restarting...**
Can you help me with this?
Already solved by add comment in /etc/nginx/sites-enabled/default on the line **"listen [::]:80 default_server;"**

Still have a problem with mono **Service crashed with exit code 255. Restarting...**
Can you help me with this?

**Comment by ghost** [comment]
@GrexAut 
Is libnovdave the correct version? That it is not a **arm** version that you have in your build?

**Comment by GrexAut** [comment]
This is not an arm version. It is for x86-64

**Comment by ghost** [comment]
@GrexAut 
Any idea why this is not running on my macbookpro or synology docker?
Is it running on your pc / server?
Thank you for the answers.
